=== kaushalmeena/chat-buddy/brain/brain.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="knowledge">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="category" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="pattern"/>
                            <xs:element name="template">
                                <xs:complexType mixed="true">
                                    <xs:sequence>
                                        <xs:element name="random" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element type="xs:string" name="li" maxOccurs="unbounded" minOccurs="0"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element type="xs:int" name="action" minOccurs="0"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== kaushalmeena/chat-buddy/app/public/brain/brain.xml
<?xml version="1.0" encoding="UTF-8"?>
<knowledge xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="brain.xsd">
  <category>
    <pattern>hello</pattern>
    <template>
      <random>
        <li>Hello there, human.</li>
        <li>Hey, how are you?</li>
        <li>Hi there.</li>
        <li>Hello. :)</li>
      </random>
    </template>
  </category>
  <category>
    <pattern>how are you</pattern>
    <template>
      <random>
        <li>I'm great, how are you?</li>
        <li>I'm good, you?</li>
        <li>Good :) you?</li>
        <li>Great! You?</li>
        <li>I'm fine, thanks for asking!</li>
      </random>
    </template>
  </category>
  <category>
    <pattern>what are you</pattern>
    <template>
      <random>
        <li>I'm a bot, silly!</li>
        <li>I am an artificial being.</li>
        <li>I am bot shaped human.</li>
      </random>
    </template>
  </category>
  <category>
    <pattern>what is your age</pattern>
    <template>
      <random>
        <li>I'm forever 0 years old.</li>
        <li>Bots don't age.</li>
      </random>
    </template>
  </category>
  <category>
    <pattern>omae wa mou shindeiru</pattern>
    <template>
      Nani??
    </template>
  </category>
  <category>
    <pattern>current date</pattern>
    <template>
      <random>
        <li>Today's date is</li>
        <li>It's</li>
      </random>
    </template>
    <action>101</action>
  </category>
  <category>
    <pattern>current time</pattern>
    <template>
      <random>
        <li>Current time is</li>
        <li>It's</li>
      </random>
    </template>
    <action>102</action>
  </category>
  <category>
    <pattern>google</pattern>
    <template>Opening in newtab...</template>
    <action>103</action>
  </category>
  <category>
    <pattern>(meow|cat)</pattern>
    <template>
      <random>
        <li>Please wait...</li>
        <li>Fetching cats...</li>
        <li>(^≗ω≗^)</li>
        <li>^._.^</li>
        <li>(=｀ω´=)</li>
      </random>
    </template>
    <action>104</action>
  </category>
  <category>
    <pattern>(woof|dog)</pattern>
    <template>
      <random>
        <li>Please wait...</li>
        <li>Fetching dog...</li>
        <li>woof woof...</li>
        <li>U・ᴥ・U</li>
        <li> U ´x` U</li>
        <li> ૮ ˙ ﻌ˙ ა</li>
      </random>
    </template>
    <action>105</action>
  </category>
  <category>
    <pattern>anime</pattern>
    <template>
      <random>
        <li>Okay...</li>
        <li>Here it is...</li>
        <li>Please wait...</li>
        <li>...</li>
      </random>
    </template>
    <action>106</action>
  </category>
  <category>
    <pattern>joke</pattern>
    <template>
      <random>
        <li>Okay...</li>
        <li>Here it is...</li>
        <li>Please wait...</li>
        <li>...</li>
      </random>
    </template>
    <action>107</action>
  </category>
  <category>
    <pattern>fact</pattern>
    <template>
      <random>
        <li>Okay...</li>
        <li>Here it is...</li>
        <li>Did you know...</li>
        <li>Please wait...</li>
        <li>...</li>
      </random>
    </template>
    <action>108</action>
  </category>
  <category>
    <pattern>.*</pattern>
    <template>
      <random>
        <li>What?</li>
        <li>I didn't get what are you talking.</li>
        <li>Huh?</li>
      </random>
    </template>
  </category>
</knowledge>

=== kaushalmeena/chat-buddy/brain/brain.xml
<?xml version="1.0" encoding="UTF-8"?>
<knowledge xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="brain.xsd">
    <category>
        <pattern>Hello</pattern>
        <template>
            <random>
                <li>Hello there, human.</li>
                <li>Hey, how are you?</li>
                <li>Hi there.</li>
                <li>Hello. :)</li>
            </random>
        </template>
    </category>
    <category>
        <pattern>How are you</pattern>
        <template>
            <random>
                <li>I'm great, how are you?</li>
                <li>I'm good, you?</li>
                <li>Good :) you?</li>
                <li>Great! You?</li>
                <li>I'm fine, thanks for asking!</li>
            </random>
        </template>
    </category>
    <category>
        <pattern>what are you</pattern>
        <template>
            <random>
                <li>I'm a bot, silly!</li>
                <li>I am an artificial being.</li>
                <li>I am bot shaped human.</li>
            </random>
        </template>
    </category>
    <category>
        <pattern>what is your age</pattern>
        <template>
            <random>
                <li>I'm forever 0 years old.</li>
                <li>Bots don't age.</li>
            </random>
        </template>
    </category>
    <category>
        <pattern>tell me today's date</pattern>
        <template>
            <random>
                <li>Today's date is</li>
                <li>Its</li>
            </random>
        </template>
        <action>101</action>
    </category>
    <category>
        <pattern>tell me current time</pattern>
        <template>
            <random>
                <li>Current time is</li>
                <li>Its</li>
            </random>
        </template>
        <action>102</action>
    </category>
    <category>
        <pattern>open google</pattern>
        <template>
            Opening in newtab...
        </template>
        <action>103</action>
    </category>
    <category>
        <pattern>fetch news</pattern>
        <template>
            <random>
                <li>Please wait...</li>
                <li>Fetching news...</li>
                <li>It may take some moments...</li>
                <li>...</li>
            </random>
        </template>
        <action>104</action>
    </category>
    <category>
        <pattern>fetch weather</pattern>
        <template>
            <random>
                <li>Please wait...</li>
                <li>Fetching weather...</li>
                <li>It may take some moments...</li>
                <li>...</li>
            </random>
        </template>
        <action>105</action>
    </category>
    <category>
        <pattern>tell me a joke</pattern>
        <template>
            <random>
                <li>Okay...</li>
                <li>Here it is...</li>
                <li>Please wait...</li>
                <li>...</li>
            </random>
        </template>
        <action>106</action>
    </category>
    <category>
        <pattern>tell me a fact</pattern>
        <template>
            <random>
                <li>Okay...</li>
                <li>Here it is...</li>
                <li>Did you know...</li>
                <li>Please wait...</li>
                <li>...</li>
            </random>
        </template>
        <action>107</action>
    </category>
    <category>
        <pattern>.*</pattern>
        <template>
            <random>
                <li>What?</li>
                <li>I didn't get what are you talking.</li>
                <li>Huh?</li>
            </random>
        </template>
    </category>
</knowledge>
